### ISSUE TITLE
Design diagnostics public API

### ISSUE THREAD

**Issue by wagdav** [wagdav/tcvpy#15]
Now that the library supports some diagnostics, a semi-formal uniform diagnostics API should be defined and implemented.

**Comment by nicolavianello** [comment]
Can you be more specific? I have also implemented the fast reciprocating diagnostic but as one of the foundamental part of this diagnostic are the profiles, I use the eqtools for properly handling transformation from (R,Z) to rho so I'm reluctant to put it on the master
